=== dret/OReilly2020NYdemo/src/guide.dtd
<!ENTITY % content '(title, teaser, text)' >
<!ELEMENT title (#PCDATA) >
<!ELEMENT teaser (#PCDATA) >
<!ELEMENT text (p|ul)+ >
<!ELEMENT p (#PCDATA|cite)* >
<!ELEMENT ul (li)+ >
<!ELEMENT li (#PCDATA) >
<!ELEMENT cite EMPTY >
<!ATTLIST cite
  ref NMTOKEN #REQUIRED >

<!ELEMENT guide (guidelines, resources) >
<!ELEMENT guidelines (guideline+) >
<!ELEMENT guideline (%content;, what+) >
<!ATTLIST guideline
  id NMTOKEN #REQUIRED >
<!ELEMENT what (%content;, how+) >
<!ATTLIST what
  id NMTOKEN #REQUIRED >
<!ELEMENT how (%content;) >
<!ATTLIST how
  id NMTOKEN #REQUIRED >
<!ELEMENT resources (resource+) >
<!ELEMENT resource (#PCDATA) >
<!ATTLIST resource
  id NMTOKEN #REQUIRED
  title CDATA #REQUIRED
  href CDATA #REQUIRED >

=== dret/OReilly2020NYdemo/src/guide.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "guide.dtd">
<?xml-stylesheet type="text/xsl" href="guide.xsl"?>
<guide>
  <guidelines>
    <guideline id="change-management-policy">
      <title>Change Management Policy</title>
      <teaser>APIs should be explicit about how changes to the API are managed and communicated.</teaser>
      <text>
        <p>One of the typical goals of APIs is to cleanly and clearly decouple how a capability is provided, and how it is consumed. The API becomes the only interface that exists between the producer and the consumer. This decoupling enables a more agile landscape of evolving products and product users in general, and one of the aspects is that producers and consumers can evolve their products individually, based on their needs and timelines.</p>
        <p>With API products and their consumers changing individually, it is important to have a well-defined and documented process how changes in the API are communicated and engineered. The goal is to balance two factors. One factor is the ease of consumption so that consumers do not have to worry about their products being disrupted because an API they are using is changing and breaking it. The second factor is the ease of production where the API product owners want to be able to evolve their product, without having to coordinate with all consumers of the API, and having to wait for them to make changes.</p>
        <p>There are different ways how this goal can be achieved, and picking one of them depends on the value that is assigned to making changes work for every single consumer, and making it easier for the API product team to evolve their API when necessary.</p>
      </text>
      <what id="design-for-evolution">
        <title>Designing for Evolution</title>
        <teaser>Design APIs so that they can evolve without breaking API consumers.</teaser>
        <text>
          <p>One possible way to handle change management is to design extensibility into the API itself. By using extensible design, changes to the API can take advantage of this extensibility, and existing consumers can continue to use the API without having to adjust.</p>
          <p>The specific design depends on the API style and technology, and on the intended extensibility. Regardless of the style and technology, design options will usually fall between these two extremes:</p>
          <ul>
            <li>No extensibility is the easiest design and allows consumers to fully rely on the API as it is when they write their code. However, with this design option there is no extensibility at all, making it impossible for the API producer to make any changes to the API without breaking existing consumers.</li>
            <li>Unlimited extensibility is the hardest design and allows producers to change everything in the API, allowing them unconstrained changes to the API. However, with this design option it becomes hard for consumers to fully implement support for all possible extensions, making it hard for consumers to use the API.</li>
          </ul>
          <p>In practice, most extensibility designs fall somewhere in the middle between these options, trying to strike a balance between allowing some extensibility, while still making it relatively easy to consume the API without having to support a very complex extensibility model. The patterns discussed in <cite ref="robust-extensibility"/> are one possible way to design for evolution.</p>
        </text>
        <how id="must-ignore-semantics">
          <title>Must Ignore Semantics</title>
          <teaser>Allow extensions but always make it safe to ignore them.</teaser>
          <text>
            <p>One relatively simple way to allow extensions is to always make it safe to ignore them. This means that anything any consumer will depend on will always be there, and it will never change its meaning. In practice, this often breaks down to the following strategies:</p>
            <ul>
              <li>Once something is defined or added, it must stay defined. The only slight exception for this is if something is optional: This means that it may or may not appear. This means that changes to the API might make this required, or not support it any more. Both are specializations of something being optional, so this is acceptable.</li>
              <li>Clearly indicate where extensions may appear, this makes it possible for consumers to write code that will not break when something new shows up.</li>
              <li>Make it safe to ignore any extension, by only defining extensions that can be safely ignored without compromising current API consumers.</li>
            </ul>
            <p>By following this strategy, it is relatively easy to define an API that evolves in a monotonic way: It only grows, and nothing is ever removed. This is also known as the "Robustness Principle" <cite ref="rfc1122"/> that asks to "be liberal in what you accept, and conservative in what you send".</p>
          </text>
        </how>
      </what>
      <what id="immutable-api-versions">
        <title>Immutable API Versions</title>
        <teaser>Never change released APIs and operate as many versions in parallel es required.</teaser>
        <text>
          <p></p>
        </text>
        <how id="automated-release-versioning">
          <title>Automated Release Versioning</title>
          <teaser>Manage releases automatically to operate many versions in parallel and route users to their versions.</teaser>
          <text>
            <p></p>
          </text>
        </how>
      </what>
    </guideline>
    <guideline id="meaningful-error-messages">
      <title>Meaningful Error Messages</title>
      <teaser>Make error messages easy to understand and provide information how to fix problems.</teaser>
      <text>
        <p>Most APIs use styles where things can go wrong. The more helpful an API is in explaining what went wrong, and how a developer or user might be able to address the problem, the more easy the API is to use.</p>
        <p>It is important to keep in mind that in case of error messages, a better Developer Experience (DX) with more helpful and clearly structured error messages directly translates into the possibility to create a better User Experience (UX). If the API only produces one generic error messages, that is the only thing that an application can display to the user. If, on the other hand, the error message is descriptive and machine-understandable, applications can at the very least display more meaningful error messages, and ideally even implement behavior that mitigates the effects of the error.</p>
      </text>
      <what id="standard-error-format">
        <title>Standard Error Format</title>
        <teaser>Use expressive and standardized error formats across APIs.</teaser>
        <text>
          <p>Error messages benefit from using a shared structure that can be used across various APIs. The structure should define the most important aspects of error messages across APIs, and should also allow extensions so that individual APIs can extend the error messages with additional details. Using a standardized error format has two main advantages.</p>
          <p>The first advantage is that it makes it easier for developers and humans to work with various APIs. It is only necessary to understand the error message format one time, and then this understanding works across all APIs. Error messages still can be made very expressive and rich by adding details through the format's extension mechanism.</p>
          <p>The second advantage is that it becomes possible to build tooling around the format. One form of tooling can be libraries that make it easier foe developers to produce or consume error messages. Another form of tooling is that it becomes much easier to observe error messages across the entire API landscape, making it relatively easy to build tooling that consumes and analyzes error messages for an entire API landscape.</p>
        </text>
        <how id="rfc-7807">
          <title>Use RFC 7807 HTTP Problem Reports</title>
          <teaser>For JSON and XML error messages, RFC 7807 provides a standardized and extensible error format.</teaser>
          <text>
            <p>The Internet standard <cite ref="rfc7807"/> defines a model for error messages for HTTP APIs. It is based on the assumption that the API is resource-oriented, and that the error message thus is a result of the standard HTTP model of interacting with resources: A client sends a request to a resource, and </p>
          </text>
        </how>
      </what>
    </guideline>
    <guideline id="service-description">
      <title>Provide Service Descriptions</title>
      <teaser>Provide machine-readable descriptions of APIs for tooling and automation.</teaser>
      <text>
        <p>...</p>
      </text>
      <what id="openapi-description">
        <title>Provide OpenAPI Descriptions for Resource-Oriented APIs</title>
        <teaser>For APIs following the resource-oriented API style, use OpenAPI to describe the individual resource URIs.</teaser>
        <text>
          <p>...</p>
        </text>
        <how id="swagger-ui-description">
          <title>Use Swagger UI Descriptions</title>
          <teaser>Swagger UI is a tool that can be used to design, discuss, and test APIs in an API-first style.</teaser>
          <text>
            <p>...</p>
          </text>
        </how>
      </what>
    </guideline>
    <guideline id="service-documentation">
      <title>Provide Service Documentation</title>
      <teaser>Provide service documentation that is appropriate for the maturity of the API and the intended audience.</teaser>
      <text>
        <p>...</p>
      </text>
      <what id="openapi-documentation">
        <title>Use OpenAPI Descriptions for Resource-Oriented APIs</title>
        <teaser>...</teaser>
        <text>
          <p>...</p>
        </text>
